model:
  base_learning_rate: 4e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 256
    ddconfig:
      double_z: False
      z_channels: 128
      resolution: 64
      in_channels: 3
      out_ch: 3
      ch: 64
      ch_mult: [1, 2, 2, 4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [8]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 30000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 24
    num_workers: 24
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /scratch/acb11361bd/StoryGan/Pororo-Dataset/train.txt
        size: 64
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: /scratch/acb11361bd/StoryGan/Pororo-VAE/taming/data/test.txt
        size: 64

